title: Gittin Jibby with it!
author: The Lang
email: your-email@domain.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This site is all about learning GitHub. I need GitHub. We all need GitHub. Git is the one Hub to rule them all.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
